version: build-{branch}-#{build}

branches:
  only:
  - cml2

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
      CONFIG: Release
      BOOST_ROOT: "C:\\Libraries\\boost"
      BOOST_LIBRARYDIR: "C:\\Libraries\\boost\\lib32-msvc-12.0"

build_script:
  - mkdir build
  - cd build
  - cmake "-G%GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS=ON -DCML_BUILD_TESTING=ON ..
  - cmake --build . --config "%CONFIG%"

test_script:
  - ctest -V --build-config "%CONFIG%"
