language: cpp

matrix:
  fast_finish: true
  include:
##    - os: linux
##      dist: trusty
##      compiler: clang
##      addons:
##        apt:
##          packages:
##          - libboost-test-dev
    - os: osx
      osx_image: xcode7.3

## before_install:
##   - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
##       brew update;
##       brew outdated boost || brew upgrade boost;
##       brew outdated cmake || brew upgrade cmake;
##     fi

before_script:
  - mkdir build 
  - cd build

script:
  - cmake -G "Unix Makefiles" -DCML_BUILD_TESTING:Bool=ON ..
  - cmake --build . --config Release
  - ctest -C Release
