language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: false
      compiler: clang
      addons:
        apt:
          packages:
          - libboost-test-dev
    - os: osx
      osx_image: xcode7

before_script:
  - mkdir build 
  - cd build

script:
  - cmake -G "Unix Makefiles" -DCML_BUILD_TESTING:Bool=ON ..
  - cmake --build . --config Release
  - ctest -C Release
